/**
 * PHOTOGRAPHS OF IMPORTED HOMES — GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Written by `node scripts/import-manufacturers.mjs manifest` from what is
 * really in `public/photos/homes/`, so a key here always has a file behind
 * it. Page heroes and one-off images are hand-written in `lib/photos.ts`.
 *
 * 192 photographs. Two kinds, and they are not equally true:
 *
 *   Pleasant Valley's exterior RENDERINGS, one per modular plan. A rendering
 *   is a drawing of a house that has not been built on your lot yet.
 *
 *   Pine Grove's photographs of the four models NERTO keeps on its lot —
 *   photographs of that model at Pine Grove, not of the particular house on
 *   River Road.
 *
 * Neither is a photograph of NERTO's yard. Photograph the lot, drop the files
 * in over these, and delete the photography note in
 * `components/site-footer.tsx`.
 */

export const importedPhotos: Record<string, string> = {
  "netr-g-4002/exterior": "/photos/homes/netr-g-4002/exterior.webp",
  "netr-g-3549/exterior": "/photos/homes/netr-g-3549/exterior.webp",
  "netr-g-3371/exterior": "/photos/homes/netr-g-3371/exterior.webp",
  "netr-g-3468/exterior": "/photos/homes/netr-g-3468/exterior.webp",
  "netr-g-3465/exterior": "/photos/homes/netr-g-3465/exterior.webp",
  "netr-g-3465/living": "/photos/homes/netr-g-3465/living.webp",
  "netr-g-3465/kitchen": "/photos/homes/netr-g-3465/kitchen.webp",
  "netr-g-3465/bedroom": "/photos/homes/netr-g-3465/bedroom.webp",
  "netr-g-3569/exterior": "/photos/homes/netr-g-3569/exterior.webp",
  "g-1799/exterior": "/photos/homes/g-1799/exterior.webp",
  "g-3450/exterior": "/photos/homes/g-3450/exterior.webp",
  "g-3450/living": "/photos/homes/g-3450/living.webp",
  "g-3450/kitchen": "/photos/homes/g-3450/kitchen.webp",
  "g-3450/bedroom": "/photos/homes/g-3450/bedroom.webp",
  "g-3462/exterior": "/photos/homes/g-3462/exterior.webp",
  "g-3465/exterior": "/photos/homes/g-3465/exterior.webp",
  "g-3557/exterior": "/photos/homes/g-3557/exterior.webp",
  "g-1941/exterior": "/photos/homes/g-1941/exterior.webp",
  "g-3554/exterior": "/photos/homes/g-3554/exterior.webp",
  "g-3564/exterior": "/photos/homes/g-3564/exterior.webp",
  "g-3452/exterior": "/photos/homes/g-3452/exterior.webp",
  "netr-g-3157/exterior": "/photos/homes/netr-g-3157/exterior.webp",
  "netr-g-3157/living": "/photos/homes/netr-g-3157/living.webp",
  "netr-g-3157/kitchen": "/photos/homes/netr-g-3157/kitchen.webp",
  "netr-g-3157/bath": "/photos/homes/netr-g-3157/bath.webp",
  "netr-g-3644/exterior": "/photos/homes/netr-g-3644/exterior.webp",
  "g-3647/exterior": "/photos/homes/g-3647/exterior.webp",
  "g-3561/exterior": "/photos/homes/g-3561/exterior.webp",
  "g-3356/exterior": "/photos/homes/g-3356/exterior.webp",
  "g-3361/exterior": "/photos/homes/g-3361/exterior.webp",
  "gh-1788/exterior": "/photos/homes/gh-1788/exterior.webp",
  "g-1785/exterior": "/photos/homes/g-1785/exterior.webp",
  "g-1787/exterior": "/photos/homes/g-1787/exterior.webp",
  "gh-1772/exterior": "/photos/homes/gh-1772/exterior.webp",
  "g-4000/exterior": "/photos/homes/g-4000/exterior.webp",
  "g-4001/exterior": "/photos/homes/g-4001/exterior.webp",
  "g-1753/exterior": "/photos/homes/g-1753/exterior.webp",
  "g-3126/exterior": "/photos/homes/g-3126/exterior.webp",
  "g-3002/exterior": "/photos/homes/g-3002/exterior.webp",
  "g-3002/living": "/photos/homes/g-3002/living.webp",
  "g-3002/kitchen": "/photos/homes/g-3002/kitchen.webp",
  "g-3653/exterior": "/photos/homes/g-3653/exterior.webp",
  "g-200/exterior": "/photos/homes/g-200/exterior.webp",
  "netr-g-3570/exterior": "/photos/homes/netr-g-3570/exterior.webp",
  "netr-g-3600/exterior": "/photos/homes/netr-g-3600/exterior.webp",
  "netr-g-3601/exterior": "/photos/homes/netr-g-3601/exterior.webp",
  "netr-g-3655/living": "/photos/homes/netr-g-3655/living.webp",
  "netr-g-3655/kitchen": "/photos/homes/netr-g-3655/kitchen.webp",
  "netr-g-3655/bedroom": "/photos/homes/netr-g-3655/bedroom.webp",
  "netr-g-3461/exterior": "/photos/homes/netr-g-3461/exterior.webp",
  "netr-g-3365/exterior": "/photos/homes/netr-g-3365/exterior.webp",
  "g-1780/exterior": "/photos/homes/g-1780/exterior.webp",
  "g-3459/exterior": "/photos/homes/g-3459/exterior.webp",
  "g-3460/exterior": "/photos/homes/g-3460/exterior.webp",
  "pg-1491/exterior": "/photos/homes/pg-1491/exterior.webp",
  "g-3602/exterior": "/photos/homes/g-3602/exterior.webp",
  "g-3566/exterior": "/photos/homes/g-3566/exterior.webp",
  "g-3645/exterior": "/photos/homes/g-3645/exterior.webp",
  "g-3646/exterior": "/photos/homes/g-3646/exterior.webp",
  "g-3660/exterior": "/photos/homes/g-3660/exterior.webp",
  "g-3661/exterior": "/photos/homes/g-3661/exterior.webp",
  "g-3603/exterior": "/photos/homes/g-3603/exterior.webp",
  "g-3358/exterior": "/photos/homes/g-3358/exterior.webp",
  "g-3365/exterior": "/photos/homes/g-3365/exterior.webp",
  "g-3154/exterior": "/photos/homes/g-3154/exterior.webp",
  "g-1740/exterior": "/photos/homes/g-1740/exterior.webp",
  "g-3556/exterior": "/photos/homes/g-3556/exterior.webp",
  "g-3552/exterior": "/photos/homes/g-3552/exterior.webp",
  "g-1836/exterior": "/photos/homes/g-1836/exterior.webp",
  "g-3553/exterior": "/photos/homes/g-3553/exterior.webp",
  "g-1892/exterior": "/photos/homes/g-1892/exterior.webp",
  "g-3649/exterior": "/photos/homes/g-3649/exterior.webp",
  "g-1802/exterior": "/photos/homes/g-1802/exterior.webp",
  "g-3658/living": "/photos/homes/g-3658/living.webp",
  "g-3658/kitchen": "/photos/homes/g-3658/kitchen.webp",
  "g-294/exterior": "/photos/homes/g-294/exterior.webp",
  "g-215/exterior": "/photos/homes/g-215/exterior.webp",
  "g-217/exterior": "/photos/homes/g-217/exterior.webp",
  "g-289/exterior": "/photos/homes/g-289/exterior.webp",
  "g-237/exterior": "/photos/homes/g-237/exterior.webp",
  "g-254/exterior": "/photos/homes/g-254/exterior.webp",
  "netr-g-679/exterior": "/photos/homes/netr-g-679/exterior.webp",
  "netr-g-652/exterior": "/photos/homes/netr-g-652/exterior.webp",
  "g-632/exterior": "/photos/homes/g-632/exterior.webp",
  "zk-1100/exterior": "/photos/homes/zk-1100/exterior.webp",
  "zk-1100/living": "/photos/homes/zk-1100/living.webp",
  "zk-1100/kitchen": "/photos/homes/zk-1100/kitchen.webp",
  "zk-1100/bedroom": "/photos/homes/zk-1100/bedroom.webp",
  "zk-1100/bath": "/photos/homes/zk-1100/bath.webp",
  "g-618/exterior": "/photos/homes/g-618/exterior.webp",
  "gh-577/living": "/photos/homes/gh-577/living.webp",
  "gh-577/kitchen": "/photos/homes/gh-577/kitchen.webp",
  "g-613/exterior": "/photos/homes/g-613/exterior.webp",
  "gh-491/exterior": "/photos/homes/gh-491/exterior.webp",
  "g-598/exterior": "/photos/homes/g-598/exterior.webp",
  "g-489/exterior": "/photos/homes/g-489/exterior.webp",
  "g-608/exterior": "/photos/homes/g-608/exterior.webp",
  "g-557/exterior": "/photos/homes/g-557/exterior.webp",
  "g-503/exterior": "/photos/homes/g-503/exterior.webp",
  "netr-g-633/exterior": "/photos/homes/netr-g-633/exterior.webp",
  "netr-g-635/exterior": "/photos/homes/netr-g-635/exterior.webp",
  "netr-g-624/exterior": "/photos/homes/netr-g-624/exterior.webp",
  "netr-g-598/exterior": "/photos/homes/netr-g-598/exterior.webp",
  "netr-g-634/exterior": "/photos/homes/netr-g-634/exterior.webp",
  "netr-g-636/exterior": "/photos/homes/netr-g-636/exterior.webp",
  "netr-g-613/exterior": "/photos/homes/netr-g-613/exterior.webp",
  "netr-g-618/exterior": "/photos/homes/netr-g-618/exterior.webp",
  "g-16-678/exterior": "/photos/homes/g-16-678/exterior.webp",
  "g-16-624/exterior": "/photos/homes/g-16-624/exterior.webp",
  "g-16-625/exterior": "/photos/homes/g-16-625/exterior.webp",
  "gh-16-496/exterior": "/photos/homes/gh-16-496/exterior.webp",
  "g-16-631/exterior": "/photos/homes/g-16-631/exterior.webp",
  "g-16-634/exterior": "/photos/homes/g-16-634/exterior.webp",
  "g-16-628/exterior": "/photos/homes/g-16-628/exterior.webp",
  "g-16-630/exterior": "/photos/homes/g-16-630/exterior.webp",
  "g-16-606/exterior": "/photos/homes/g-16-606/exterior.webp",
  "fillmore/exterior": "/photos/homes/fillmore/exterior.webp",
  "pierce/exterior": "/photos/homes/pierce/exterior.webp",
  "reagan-ii/exterior": "/photos/homes/reagan-ii/exterior.webp",
  "knox/exterior": "/photos/homes/knox/exterior.webp",
  "harding/exterior": "/photos/homes/harding/exterior.webp",
  "mount-whitney-ii/exterior": "/photos/homes/mount-whitney-ii/exterior.webp",
  "mount-mansfield/exterior": "/photos/homes/mount-mansfield/exterior.webp",
  "salisbury-i/exterior": "/photos/homes/salisbury-i/exterior.webp",
  "salisbury-ii/exterior": "/photos/homes/salisbury-ii/exterior.webp",
  "coolidge/exterior": "/photos/homes/coolidge/exterior.webp",
  "amherst/exterior": "/photos/homes/amherst/exterior.webp",
  "kennebunk-ii/exterior": "/photos/homes/kennebunk-ii/exterior.webp",
  "wildwood-ii/exterior": "/photos/homes/wildwood-ii/exterior.webp",
  "edgewood/exterior": "/photos/homes/edgewood/exterior.webp",
  "bridgeport-ii/exterior": "/photos/homes/bridgeport-ii/exterior.webp",
  "mayfield/exterior": "/photos/homes/mayfield/exterior.webp",
  "dover/exterior": "/photos/homes/dover/exterior.webp",
  "coral-gables/exterior": "/photos/homes/coral-gables/exterior.webp",
  "manchester-ii/exterior": "/photos/homes/manchester-ii/exterior.webp",
  "new-haven/exterior": "/photos/homes/new-haven/exterior.webp",
  "mayfield-ii/exterior": "/photos/homes/mayfield-ii/exterior.webp",
  "brighton-i-a/exterior": "/photos/homes/brighton-i-a/exterior.webp",
  "chesapeake-c/exterior": "/photos/homes/chesapeake-c/exterior.webp",
  "canandaigua/exterior": "/photos/homes/canandaigua/exterior.webp",
  "clarendon/exterior": "/photos/homes/clarendon/exterior.webp",
  "flagstaff/exterior": "/photos/homes/flagstaff/exterior.webp",
  "tucson/exterior": "/photos/homes/tucson/exterior.webp",
  "tacoma/exterior": "/photos/homes/tacoma/exterior.webp",
  "tacoma-ii/exterior": "/photos/homes/tacoma-ii/exterior.webp",
  "monticello/exterior": "/photos/homes/monticello/exterior.webp",
  "clearfield-ii/exterior": "/photos/homes/clearfield-ii/exterior.webp",
  "charlotte-ii/exterior": "/photos/homes/charlotte-ii/exterior.webp",
  "asheville/exterior": "/photos/homes/asheville/exterior.webp",
  "beach-haven/exterior": "/photos/homes/beach-haven/exterior.webp",
  "cape-neddick-ii/exterior": "/photos/homes/cape-neddick-ii/exterior.webp",
  "cape-plymouth-ii/exterior": "/photos/homes/cape-plymouth-ii/exterior.webp",
  "cape-ann-ii/exterior": "/photos/homes/cape-ann-ii/exterior.webp",
  "cape-horn/exterior": "/photos/homes/cape-horn/exterior.webp",
  "cape-bayshore-ii/exterior": "/photos/homes/cape-bayshore-ii/exterior.webp",
  "cape-verde/exterior": "/photos/homes/cape-verde/exterior.webp",
  "cape-verde-ii/exterior": "/photos/homes/cape-verde-ii/exterior.webp",
  "cape-hatteras-ii/exterior": "/photos/homes/cape-hatteras-ii/exterior.webp",
  "cape-freeport-ii/exterior": "/photos/homes/cape-freeport-ii/exterior.webp",
  "cape-henery-ii/exterior": "/photos/homes/cape-henery-ii/exterior.webp",
  "oak-alley/exterior": "/photos/homes/oak-alley/exterior.webp",
  "fairvue-ii/exterior": "/photos/homes/fairvue-ii/exterior.webp",
  "gamble/exterior": "/photos/homes/gamble/exterior.webp",
  "tulip-hill/exterior": "/photos/homes/tulip-hill/exterior.webp",
  "aspendale-ii/exterior": "/photos/homes/aspendale-ii/exterior.webp",
  "belfont/exterior": "/photos/homes/belfont/exterior.webp",
  "stafford/exterior": "/photos/homes/stafford/exterior.webp",
  "riverhead-i/exterior": "/photos/homes/riverhead-i/exterior.webp",
  "riverhead-ii/exterior": "/photos/homes/riverhead-ii/exterior.webp",
  "laura-ii/exterior": "/photos/homes/laura-ii/exterior.webp",
  "shirley/exterior": "/photos/homes/shirley/exterior.webp",
  "waverly/exterior": "/photos/homes/waverly/exterior.webp",
  "astoria-ii/exterior": "/photos/homes/astoria-ii/exterior.webp",
  "felicity/exterior": "/photos/homes/felicity/exterior.webp",
  "fox-haven/exterior": "/photos/homes/fox-haven/exterior.webp",
  "poplar-hall/exterior": "/photos/homes/poplar-hall/exterior.webp",
  "westfield/exterior": "/photos/homes/westfield/exterior.webp",
  "chelsea/exterior": "/photos/homes/chelsea/exterior.webp",
  "pebble-hill/exterior": "/photos/homes/pebble-hill/exterior.webp",
  "cascade/exterior": "/photos/homes/cascade/exterior.webp",
  "grand-teton/exterior": "/photos/homes/grand-teton/exterior.webp",
  "sweet-azalea/exterior": "/photos/homes/sweet-azalea/exterior.webp",
  "dogwood/exterior": "/photos/homes/dogwood/exterior.webp",
  "jasmine/exterior": "/photos/homes/jasmine/exterior.webp",
  "magnolia/exterior": "/photos/homes/magnolia/exterior.webp",
  "mulberry/exterior": "/photos/homes/mulberry/exterior.webp",
  "wisteria/exterior": "/photos/homes/wisteria/exterior.webp",
  "big-bend-adu/exterior": "/photos/homes/big-bend-adu/exterior.webp",
  "sequoia-adu/exterior": "/photos/homes/sequoia-adu/exterior.webp",
  "denali-adu/exterior": "/photos/homes/denali-adu/exterior.webp",
  "zion-adu/exterior": "/photos/homes/zion-adu/exterior.webp",
  "glacier-adu/exterior": "/photos/homes/glacier-adu/exterior.webp",
};
